name: Python Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  python-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff black bandit pytype

    - name: Run Pylint
      run: |
        pylint **/*.py || true

    - name: Run Ruff
      run: |
        ruff check . || true

    - name: Run Black
      run: |
        black --check . || true

    - name: Run Bandit
      run: |
        bandit -r . || true

    - name: Run Pytype
      run: |
        pytype . || true

    - name: Check for errors
      run: |
        echo "Checking for errors"
        if grep -qE "pylint|ruff|black|bandit|pytype" <<< "$(jobs.*.outcome)"; then
          echo "One or more tools found issues."
          exit 1
        fi

